# Generated by Django 4.0.5 on 2022-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totla_sum',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'открыт'), ('in_process', 'В прооцесск'), ('canceled', 'Отменен'), ('Finished', 'Завершонный')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
